/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Estudiantes
 */
public class Bienvenida extends javax.swing.JFrame {

    private int nit;
    /**
     * Creates new form Bienvenida
     */
    public Bienvenida() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RestoNIT = new javax.swing.JTextField();
        Titulo = new javax.swing.JLabel();
        IngreseNIT = new javax.swing.JLabel();
        Aceptar = new javax.swing.JButton();
        PrimerDigitoNIT = new javax.swing.JTextField();
        Separador = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(338, 338));
        setMinimumSize(new java.awt.Dimension(338, 338));
        setPreferredSize(new java.awt.Dimension(338, 338));
        getContentPane().setLayout(null);

        RestoNIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestoNITActionPerformed(evt);
            }
        });
        getContentPane().add(RestoNIT);
        RestoNIT.setBounds(50, 230, 88, 20);

        Titulo.setText("BIENVENIDO A SU BANCO PREFERIDO");
        getContentPane().add(Titulo);
        Titulo.setBounds(60, 10, 250, 20);

        IngreseNIT.setText("Ingrese Nit Tarjeta: ");
        getContentPane().add(IngreseNIT);
        IngreseNIT.setBounds(10, 190, 110, 30);

        Aceptar.setText("ACEPTAR");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        getContentPane().add(Aceptar);
        Aceptar.setBounds(210, 220, 100, 20);

        PrimerDigitoNIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimerDigitoNITActionPerformed(evt);
            }
        });
        getContentPane().add(PrimerDigitoNIT);
        PrimerDigitoNIT.setBounds(20, 230, 19, 20);

        Separador.setText("-");
        getContentPane().add(Separador);
        Separador.setBounds(40, 230, 10, 14);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        Fondo.setMaximumSize(new java.awt.Dimension(338, 338));
        Fondo.setPreferredSize(new java.awt.Dimension(338, 338));
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 340, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RestoNITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestoNITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RestoNITActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        try {
            
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_AceptarActionPerformed

    private void PrimerDigitoNITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimerDigitoNITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrimerDigitoNITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel IngreseNIT;
    private javax.swing.JTextField PrimerDigitoNIT;
    private javax.swing.JTextField RestoNIT;
    private javax.swing.JLabel Separador;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
