/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Cliente;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeisson
 */
public class ImpresionCliente extends javax.swing.JFrame {

    private Cliente user;
    private int monto;
    /**
     * Creates new form ImpresionCliente
     */
    public ImpresionCliente() {
        initComponents();
    }
    
    public void Imprimir(){
        JOptionPane.showMessageDialog(null, "Monto: "+this.monto+" Nombre: "+ this.user.getNombre()+
                " Dinero: "+ this.user.getDinero());
    }
    
    public ImpresionCliente(Cliente user, int monto) {
        this.user=user;
        this.monto=monto;
        initComponents();
        retiro.setText(Integer.toString(monto));
        saldo.setText(Integer.toString(user.getDinero()));
        nitTarjeta.setText(Integer.toString(user.getNit()));
        numCajero.setText("001");
        Date fecha= new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        fechaHora.setText(sdf.format(fecha));
        
        //Imprimir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        imprimir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fechaHora = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nitTarjeta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        numCajero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        retiro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        saldo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        panel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 335));
        setMinimumSize(new java.awt.Dimension(400, 335));
        setPreferredSize(new java.awt.Dimension(400, 335));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel2.setText("BANCO X");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 20, 140, 50);

        imprimir.setText("IMPRIMIR");
        imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirActionPerformed(evt);
            }
        });
        getContentPane().add(imprimir);
        imprimir.setBounds(240, 223, 130, 30);

        jLabel3.setText("FECHA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 70, 40, 20);

        jLabel4.setText("HORA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 70, 40, 20);

        fechaHora.setEditable(false);
        getContentPane().add(fechaHora);
        fechaHora.setBounds(10, 90, 150, 30);

        jLabel6.setText("No.Tarjeta");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 130, 60, 30);

        nitTarjeta.setEditable(false);
        getContentPane().add(nitTarjeta);
        nitTarjeta.setBounds(70, 130, 160, 30);

        jLabel5.setText("CAJERO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 70, 50, 20);

        numCajero.setEditable(false);
        getContentPane().add(numCajero);
        numCajero.setBounds(180, 90, 40, 30);

        jLabel1.setText("EXTRACCION CUENTA DE AHORROS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 170, 230, 20);

        jLabel7.setText("Valor Retirado");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 190, 80, 30);

        retiro.setEditable(false);
        getContentPane().add(retiro);
        retiro.setBounds(90, 190, 120, 30);

        jLabel8.setText("Saldo");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 234, 50, 20);

        saldo.setEditable(false);
        getContentPane().add(saldo);
        saldo.setBounds(90, 230, 120, 30);

        jLabel9.setText("GRACIAS POR USAR NUESTROS SERVCIOS!");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 270, 270, 20);

        panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoBlanco.jpg"))); // NOI18N
        panel.setMaximumSize(new java.awt.Dimension(500, 334));
        panel.setMinimumSize(new java.awt.Dimension(500, 334));
        panel.setPreferredSize(new java.awt.Dimension(500, 334));
        getContentPane().add(panel);
        panel.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirActionPerformed
        Bienvenida ir=new Bienvenida();
        ir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_imprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImpresionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImpresionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImpresionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImpresionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImpresionCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fechaHora;
    private javax.swing.JButton imprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nitTarjeta;
    private javax.swing.JTextField numCajero;
    private javax.swing.JLabel panel;
    private javax.swing.JTextField retiro;
    private javax.swing.JTextField saldo;
    // End of variables declaration//GEN-END:variables
}
