/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.DAO.EstadoCajeroDAO;
import Controlador.FuncionesAdmi;
import Modelo.Administrador;
import Modelo.Cliente;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeisson
 */
public class IngresarMonto extends javax.swing.JFrame {
    
    private int cantidad;
    private int admin;
    private Cliente  user;
    private int opcion;
    private String mensaje;
    /**
     * Creates new form IngresarMonto
     */
    public IngresarMonto() {
        admin=0;
        user=null;
        initComponents();
    }
    
    public IngresarMonto(int admin,int opcion) {
        this.admin=admin;
        user=null;
        this.opcion= opcion;
        initComponents();
    }
    
    public IngresarMonto(Cliente user) {
        this.user=user;
        admin=0;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Volver = new javax.swing.JButton();
        OK = new javax.swing.JButton();
        Monto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 334));
        setMinimumSize(new java.awt.Dimension(450, 334));
        getContentPane().setLayout(null);

        Volver.setText("Cancelar Operación");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver);
        Volver.setBounds(100, 240, 180, 40);

        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        getContentPane().add(OK);
        OK.setBounds(40, 150, 80, 50);

        Monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MontoKeyTyped(evt);
            }
        });
        getContentPane().add(Monto);
        Monto.setBounds(180, 150, 130, 50);

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel2.setText("DIGITE LA CANTIDAD");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 20, 260, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Digite.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 490, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MontoKeyTyped
        char c=evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
    }//GEN-LAST:event_MontoKeyTyped

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        if(Monto.getText().length()>0){
            cantidad=Integer.parseInt(Monto.getText());
            if(user!=null){
                EstadoCajeroDAO estado = new EstadoCajeroDAO();
                int cantidadMaximaHoy;
                cantidadMaximaHoy= estado.consultarTopeHoy();
                
                if(cantidad<=cantidadMaximaHoy){
                    IngresoContraseña ingresar = new IngresoContraseña(user);
                    ingresar.setMonto(cantidad);
                    ingresar.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo realizar el retiro: Maximo retiro actual permitiido es: "+ cantidadMaximaHoy);
                }
                
            }else if(admin!=0){
                if(opcion==1){
                    FuncionesAdmi funcion = new FuncionesAdmi();
                    try {
                        boolean respuesta=funcion.ingresarDinero(cantidad);
                        if(respuesta==true){
                            mensaje="Dinero ingresado correctamente: ";
                            ImpresionAdmin ia=new ImpresionAdmin(admin,Integer.parseInt(Monto.getText()),mensaje);
                            ia.setVisible(true);
                            this.dispose();
                        }else{
                            JOptionPane.showMessageDialog(null, "No se pudo ingresar el dinero");
                        }
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(IngresarMonto.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                    FuncionesAdmi funcion = new FuncionesAdmi();
                    try {
                        boolean respuesta=funcion.modificarTopeHoy(cantidad);
                        if(respuesta==true){
                            
                            mensaje="Tope diario modificado: ";
                            ImpresionAdmin ia=new ImpresionAdmin(admin,Integer.parseInt(Monto.getText()),mensaje);
                            ia.setVisible(true);
                            this.dispose();
                        }else{
                            JOptionPane.showMessageDialog(null, "No se pudo modificar el tope");
                        }
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(IngresarMonto.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "ERROR!! Usuario y administrador nulo.");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Digite por favor un valor");
        }
        
    }//GEN-LAST:event_OKActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        Bienvenida retorno=new Bienvenida();
        retorno.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarMonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarMonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarMonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarMonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarMonto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Monto;
    private javax.swing.JButton OK;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
