/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ValidarContraseñas;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeisson
 */
public class IngresarNIT extends javax.swing.JFrame {

    private int nit;
    private int admin;
    /**
     * Creates new form IngresarNIT
     */
    public IngresarNIT() {
        initComponents();
    }
    
    public IngresarNIT(int admin) {
        this.admin=admin;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OK = new javax.swing.JButton();
        RestoNIT = new javax.swing.JTextField();
        PrimerDigito = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        VOLVER = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 334));
        setMinimumSize(new java.awt.Dimension(450, 334));
        getContentPane().setLayout(null);

        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        getContentPane().add(OK);
        OK.setBounds(40, 150, 70, 40);

        RestoNIT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RestoNITKeyTyped(evt);
            }
        });
        getContentPane().add(RestoNIT);
        RestoNIT.setBounds(190, 150, 190, 30);

        PrimerDigito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PrimerDigitoKeyTyped(evt);
            }
        });
        getContentPane().add(PrimerDigito);
        PrimerDigito.setBounds(140, 150, 40, 30);

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel2.setText("DIGITE EL NIT");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 20, 180, 40);

        VOLVER.setText("Cancelar Operación");
        VOLVER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOLVERActionPerformed(evt);
            }
        });
        getContentPane().add(VOLVER);
        VOLVER.setBounds(120, 250, 200, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Digite.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RestoNITKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RestoNITKeyTyped
        char c=evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
        if (RestoNIT.getText().length()== 8)evt.consume();
        
    }//GEN-LAST:event_RestoNITKeyTyped

    private void PrimerDigitoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrimerDigitoKeyTyped
        char c=evt.getKeyChar();
        if(c<'1'||c>'2')evt.consume();
        if (PrimerDigito.getText().length()== 1)evt.consume();
    }//GEN-LAST:event_PrimerDigitoKeyTyped

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        
        if(PrimerDigito.getText().length()==1 && RestoNIT.getText().length()==8){
            
            nit=Integer.parseInt(PrimerDigito.getText()+ RestoNIT.getText());
            ValidarContraseñas val = new ValidarContraseñas();
            try {
                boolean respuesta = val.ReactivarTarjetas(nit);
                if(respuesta==true){
                    JOptionPane.showMessageDialog(null, "Se reactivo satisfactoriamente!!");
                    MenuCliente mc = new MenuCliente();
                    mc.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "No se reactivo satisfactoriamente!!");
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(IngresarNIT.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }else{
            JOptionPane.showMessageDialog(null, "NIT invalido");
            JOptionPane.showMessageDialog(null, "FORMATO: X-XXXXXXX");
        }
    }//GEN-LAST:event_OKActionPerformed

    private void VOLVERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOLVERActionPerformed
        Bienvenida retorno=new Bienvenida();
        retorno.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VOLVERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarNIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarNIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarNIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarNIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarNIT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OK;
    private javax.swing.JTextField PrimerDigito;
    private javax.swing.JTextField RestoNIT;
    private javax.swing.JButton VOLVER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
